version: '3.8'

services:
  twintto_db:
    image: mongo:4.4.1
    container_name: twintto_db
    restart: always
    ports:
      - '${DB_PORT}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - twintto-mongo-data:/data/db

  twintto_api:
    image: node:12.19.0-alpine3.12
    container_name: twintto_api
    restart: always
    ports:
      - '${APP_PORT}:5858'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    links:
      - twintto_db
    command: sh -c './wait-for twintto_db:27017 -- yarn && yarn global add pm2 && yarn cache clean && yarn start'

volumes:
  twintto-mongo-data:
